name: check code quality
#inputs:
#  who-to-greet:  # id of input
#    description: 'Who to greet'
#    required: true
#    default: 'World'
#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: "1.20"
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.53.3

    - name: run go vet
      uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: "1.20"
    - run: make vet

    - name: run unit tests
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: "1.20"
    - run: make test
