name: run acceptance tests

on:
  label:
    types:
      - created

jobs:
  acc_tests:
    name: run go vet
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - run: make acceptance
