name: check code quality

on:
  pull_request:
    types:
      - opened
      - closed
      - edited
      - reopened
      - synchronize
  label:
    types:
      - created
      - deleted
      - edited

jobs:
  acc_tests:
    name: run acceptance tests
    runs-on: ubuntu-22.04
    if: ${{ github.event.label.name == 'post' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - run: make acceptance
