name: check code quality

on:
  label:
    types:
      - created

jobs:
  acc_tests:
    name: run acceptance tests
    runs-on: ubuntu-22.04
    if: ${{ github.event.label.name == 'post' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - run: make acceptance
