name: check code quality

on:
  pull_request:
    types:
      - opened
      - closed
      - edited
      - reopened
      - synchronize
      - labeled

jobs:
  lint:
    name: run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.53.3
  vet:
    name: run go vet
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - run: make vet
  unit_tests:
    name: run unit tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - run: make test
  acc_tests:
    name: run acceptance tests
    runs-on: ubuntu-22.04
    if: ${{ github.event.label.name == 'post' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - run: make acceptance
