name: run tests

on:
  pull_request:
    types:
      - labeled

jobs:
  acc_tests:
    name: acceptance tests
    runs-on: ubuntu-22.04
    if: ${{ github.event.label.name == 'post' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - run: make acceptance
        env:
          AUTH_URL: ${{ secrets.AUTH_URL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USERNAME: ${{ secrets.USERNAME }}
          USER_DOMAIN_NAME: ${{ secrets.USER_DOMAIN_NAME }}
          FUNCTEST_PROJECT_NAME: ${{ secrets.FUNCTEST_PROJECT_NAME }}

