name: run tests

on:
  pull_request:
    types:
      - labeled
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true


jobs:
  acc_tests:
    name: acceptance tests
    runs-on: ubuntu-22.04
    environment: tests
    if: ${{ github.event.label.name == 'post' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - uses: .github/workflows/reusable-workflow.yml
      - run: make acceptance
        env:
          OS_AUTH_URL: ${{ secrets.AUTH_URL }}
          OS_DOMAIN_NAME: ${{ secrets.USER_DOMAIN_NAME }}
          OS_PASSWORD: ${{ secrets.PASSWORD }}
          OS_USERNAME: ${{ secrets.USERNAME }}
          OS_PROJECT_NAME: ${{ vars.FUNCTEST_PROJECT_NAME }}
          OS_REGION: "eu-de"
